import Head from 'next/head'
import Card from '../components/card/Card';
import Debug from '../components/Debug';
import InfoBar from '../components/InfoBar';
import ModalLose from '../components/modal/ModalLose';
import ModalStartGame from '../components/modal/ModalStartGame';
import ModalWin from '../components/modal/ModalWin';
import { useGameContext } from '../context/GameContext';

import FRUITS from '../data/fruits'

export default function Home({ players }) {
  const { cards, founded, activateTimer } = useGameContext()

  return (
    <>
      <Head>
        <title>Memory oClock</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="container mx-auto">
        {/* <Debug /> */}
        <div onClick={() => founded.length < FRUITS.length ? activateTimer() : false} className="grid gap-6 grid-cols-6 align-center">
          {cards && cards.map((fruit, key) => <Card id={key} key={key} fruit={fruit} />)}
        </div>

        <InfoBar />
      </div>
      <ModalStartGame />
      <ModalWin />
      <ModalLose />
    </>
  )
}

