import Head from 'next/head'
import { useEffect, useState } from 'react';
import Card from '../components/card/Card';
import Debug from '../components/Debug';
import ModalWin from '../components/dialog/ModalWin';

const FRUITS = ["red-apple", "banana", "orange", "lime", "pomegranate",
  "apricot", "lemon", "strawberry", "green-apple", "peach", "grape",
  "watermelon", "plum", "pear", "cherry", "raspberry", "mango", "cherry-yellow"]

const FRUITS_LOW = ["red-apple", "banana", "orange"]


let shuffleFruits = array => array.sort(() => 0.5 - Math.random());


export default function Home() {
  const [cards, setCards] = useState([])
  const [counter, setCounter] = useState(10)
  const [activeCounter, setActiveCounter] = useState(false)


  useEffect(() => {
    let fruits = [...shuffleFruits(FRUITS_LOW), ...shuffleFruits(FRUITS_LOW)]
    setCards(fruits)
  }, [])


  useEffect(() => {
    if (activeCounter) {
      const intervalId = setInterval(() => { setCounter(counter - 1) }, 1000)
      console.log(counter)
      if (counter == 0) {
        setActiveCounter(false)
      }
      return () => clearInterval(intervalId)
    }

  }, [counter, activeCounter])

  return (
    <>
      <Head>
        <title>Memory oClock</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="container mx-auto">
        {/* <Debug /> */}
        <div onClick={() => setActiveCounter(true)} className="grid gap-6 grid-cols-6 align-center">
          {cards && cards.map((fruit, key) => <Card id={key} key={key} fruit={fruit} />)}
        </div>
        <div className="flex border rounded-md p-5 ">
          <div className="flex-1">
            TEMPS RESTANT : {counter}
          </div>
          <div className="flex-1">xxx</div>
        </div>
      </div>
      <ModalWin />
    </>
  )
}
